[workspace]
default-members = ["rsql_cli", "rsql_core", "rsql_drivers", "rsql_formatters"]
members = ["rsql_cli", "rsql_core", "rsql_drivers", "rsql_formatters"]
resolver = "2"

[workspace.package]
authors = ["Brian Heineman <brian.heineman@gmail.com>"]
categories = ["database"]
edition = "2021"
keywords = ["database", "mysql", "postgresql", "sql", "sqlite"]
license = "Apache-2.0 OR MIT"
repository = "https://github.com/theseus-rs/rsql"
version = "0.14.0"

[workspace.dependencies]
ansi_colours = "1.2.3"
anyhow = "1.0.93"
arboard = "3.4.1"
async-trait = "0.1.82"
axoupdater = "0.8.1"
base64 = "0.22.1"
bit-vec = "0.6.3"
chrono = "0.4.38"
clap = "4.5.20"
clap-stdin = "0.5.1"
clearscreen = "3.0.0"
colored = "2.1.0"
config = "0.14.0"
criterion = "0.5.1"
csv = "1.3.0"
dark-light = "1.1.1"
dirs = "5.0.1"
dotenvy = "0.15.7"
duckdb = "0.10.2"
form_urlencoded = "1.2.1"
futures-util = "0.3.31"
indexmap = "2.6.0"
indicatif = "0.17.8"
indoc = "2.0.5"
inquire = "0.7.5"
jwt-simple = { version = "0.12.10", default-features = false }
libsql = "0.5.0"
mockall = "0.13.0"
num-format = "0.4.4"
os_info = "3.8.2"
postgresql_embedded = "0.17.2"
quick-xml = "0.36.2"
regex = "1.11.1"
reqwest = "0.12.8"
rusqlite = "0.30.0"
rust_decimal = "1.35.0"
rust-i18n = "3.1.2"
rustyline = "14.0.0"
semver = "1.0.23"
serde = "1.0.214"
serde_json = "1.0.132"
serde_yaml = "0.9.34"
sha2 = "0.10.8"
sqlx = "0.7.4"
sqlparser = "0.51.0"
supports-color = "3.0.1"
sys-locale = "0.3.2"
syntect = "5.2.0"
tabled = "0.16.0"
tempfile = "3.11.0"
termbg = "0.6.0"
test-log = "0.2.16"
testcontainers = "0.23.1"
testcontainers-modules = "0.11.3"
thiserror = "2.0.0"
tiberius = { version = "0.12.3", default-features = false }
tokio = "1.41.1"
tokio-postgres = "0.7.12"
tokio-util = "0.7.12"
tracing = "0.1.40"
tracing-appender = "0.2.3"
tracing-indicatif = "0.3.6"
tracing-subscriber = "0.3.18"
unicode-width = "0.2.0"
url = "2.5.3"
uuid = "1.11.0"
wiremock = "0.6.2"

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
strip = true

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

[workspace.metadata.release]
shared-version = true
dependent-version = "upgrade"
tag-name = "v{{version}}"
