[package]
authors.workspace = true
categories.workspace = true
description = "rsql core library for creating a command line SQL interfaces"
edition.workspace = true
keywords.workspace = true
license.workspace = true
name = "rsql_core"
repository.workspace = true
version.workspace = true

[dependencies]
anyhow = { workspace = true }
ansi_colours = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
clap-stdin = { workspace = true, features = ["tokio"] }
clearscreen = { workspace = true }
colored = { workspace = true }
config = { workspace = true }
csv = { workspace = true }
dark-light = { workspace = true }
dirs = { workspace = true }
indexmap = { workspace = true, features = ["serde"] }
indicatif = { workspace = true }
indoc = { workspace = true }
lazy_static = { workspace = true }
num-format = { workspace = true }
prettytable = { workspace = true }
regex = { workspace = true }
rsql_drivers = { path = "../rsql_drivers", version = "0.8.0", features = ["all"] }
rust-i18n = { workspace = true }
rustyline = { workspace = true }
quick-xml = { workspace = true, features = ["serialize"] }
serde_json = { workspace = true, features = ["preserve_order"] }
serde_yaml = { workspace = true }
supports-color = { workspace = true }
sys-locale = { workspace = true }
syntect = { workspace = true }
tempfile = { workspace = true }
termbg = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "macros"] }
tracing = { workspace = true }
tracing-appender = { workspace = true }
tracing-indicatif = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "tracing-log"] }
unicode-width = { workspace = true }
url = { workspace = true }

[dev-dependencies]
criterion = { workspace = true, features = ["async_tokio"] }
mockall = { workspace = true }
test-log = { workspace = true }
tokio = { workspace = true }

[features]
all = ["mysql", "postgres", "postgresql", "rusqlite", "sqlite"]
default = []
libsql = [
    "rsql_drivers/libsql",
]
mysql = [
    "rsql_drivers/mysql",
]
postgres = [
    "rsql_drivers/postgres",
]
postgresql = [
    "rsql_drivers/postgresql",
]
rusqlite = [
    "rsql_drivers/rusqlite",
]
sqlite = [
    "rsql_drivers/sqlite",
]

[lints.clippy]
unwrap_used = "deny"

[package.metadata.docs.rs]
features = ["all"]
targets = ["x86_64-unknown-linux-gnu"]

[[bench]]
harness = false
name = "bench_main"
