[package]
authors.workspace = true
categories.workspace = true
description = "rsql core library for creating a command line SQL interfaces"
edition.workspace = true
keywords.workspace = true
license.workspace = true
name = "rsql_core"
repository.workspace = true
version.workspace = true

[dependencies]
ansi_colours = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
base64 = { workspace = true }
bit-vec = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
clap = { workspace = true, features = ["derive", "env"] }
clap-stdin = { workspace = true, features = ["tokio"] }
clearscreen = { workspace = true }
colored = { workspace = true }
config = { workspace = true }
csv = { workspace = true }
dark-light = { workspace = true }
dirs = { workspace = true }
form_urlencoded = { workspace = true }
indexmap = { workspace = true, features = ["serde"] }
indicatif = { workspace = true }
indoc = { workspace = true }
lazy_static = { workspace = true }
num-format = { workspace = true }
prettytable = { workspace = true }
postgresql_archive = { workspace = true, optional = true }
postgresql_embedded = { workspace = true, optional = true }
regex = { workspace = true }
rusqlite = { workspace = true, features = ["bundled-full"], optional = true }
rust_decimal = { workspace = true }
rust-i18n = { workspace = true }
rustyline = { workspace = true }
quick-xml = { workspace = true, features = ["serialize"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["preserve_order"] }
serde_yaml = { workspace = true }
sqlx = { workspace = true, features = ["bit-vec", "chrono", "json", "macros", "runtime-tokio", "rust_decimal", "time", "uuid"], optional = true }
supports-color = { workspace = true }
sys-locale = { workspace = true }
syntect = { workspace = true }
termbg = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "macros"] }
tracing = { workspace = true }
tracing-appender = { workspace = true }
tracing-indicatif = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "tracing-log"] }
unicode-width = { workspace = true }
url = { workspace = true }
uuid = { workspace = true, features = ["serde", "v4"] }

[dev-dependencies]
criterion = { workspace = true, features = ["async_tokio"] }
mockall = { workspace = true }
tempfile = { workspace = true }
test-log = { workspace = true }
tokio = { workspace = true }

[features]
all = ["postgresql", "rusqlite", "sqlite"]
default = []
postgresql = [
    "dep:postgresql_archive",
    "dep:postgresql_embedded",
    "dep:sqlx",
    "sqlx/postgres",
]
rusqlite = [
    "dep:rusqlite",
]
sqlite = [
    "dep:sqlx",
    "sqlx/sqlite",
]

[lints.clippy]
unwrap_used = "deny"

[package.metadata.docs.rs]
features = ["all"]
targets = ["x86_64-unknown-linux-gnu"]

[[bench]]
harness = false
name = "bench_main"
